// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEPSeYpUKwwHtoF-ny3BSxioXWRj0m24M',
    appId: '1:1036791968983:web:f93a32bf54e9f7aac86c92',
    messagingSenderId: '1036791968983',
    projectId: 'emart-utem',
    authDomain: 'emart-utem.firebaseapp.com',
    databaseURL: 'https://emart-utem-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emart-utem.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDom8qPvTAoT0fs80s3K4G8CGd2hCcteIc',
    appId: '1:1036791968983:android:ac195e1adb9fcd0cc86c92',
    messagingSenderId: '1036791968983',
    projectId: 'emart-utem',
    databaseURL: 'https://emart-utem-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emart-utem.appspot.com',
  );
}
